global:
  namespace: default
  projectId: starlit-oven-379913

storage-bucket:
  name: storage-bucket-cloudfest
  versioning:
    enabled: false
  # lifecycleRuleCreate: false
  # lifecycleRule:
  #     - action:
  #         type: Delete
  #       condition:
  #         age: 7

service-account:
  createGoogleServiceAccount: true
  createKubernetesServiceAccount: true
  createWorkloadIndentity: true
  createStorageBucketPolicy: true
  annotations: {}
  name: bucket-access-sa
  bucketName: storage-bucket-cloudfest