global:
  projectId: starlit-oven-379913
  namespace: default
createGoogleServiceAccount: true
createKubernetesServiceAccount: true
createWorkloadIndentity: true
createStorageBucketPolicy: true
annotations: {}
name: my-app-sa
bucketName: storage-bucket-cloudfest

