{{- if .Values.createGoogleServiceAccount -}}
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.global.projectId }}
  name: {{ .Values.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  displayName: {{ .Values.name }}
{{- end }}