{{- if .Values.createKubernetesServiceAccount -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  {{ .Values.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "service-account.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.name }}@{{ .Values.global.projectId }}.iam.gserviceaccount.com
  spec:
{{- end }}
