global:
  projectId: "testProject"

replicaCount: 1

image:
  repository: google/cloud-sdk
  pullPolicy: IfNotPresent
  tag: "alpine"

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources: {}

serviceAccountName: my-app-sa

env: 
  - name: BUCKET_NAME
    value: "my-uniqe-storage-bucket-cloudfest"

args:
  script: 
    - /bin/sh
    - -c
    - >
      while true;
        do
          touch $(date +%m-%d-%Y-%M);
          gsutil cp $(date +%m-%d-%Y-%M) gs://$BUCKET_NAME;
          sleep 90;
        done