apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "appChart.fullname" . }}
  labels:
    {{- include "appChart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "appChart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "appChart.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "appChart.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.args.create }}
            {{- with .Values.args.script }}
          args:
            {{- toYaml . | nindent 12 }}
            {{- end}}
          {{- end }}
