global:
  namespace: default
  projectId: starlit-oven-379913

name: storage-bucket-cloudfest

versioning:
  enabled: false
lifecycleRuleCreate: false
lifecycleRule:
    - action:
        type: Delete
      condition:
        age: 7

