apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  project: default
  source:
    path: examples/argocd/apps/my-app
    repoURL: https://github.com/rudzm/cloudfest
    helm: 
      valueFiles:
      - values.yaml
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
